### ISSUE TITLE
Middleman v4 support

### ISSUE THREAD

**Issue by 5t111111** [5t111111/middleman-blog-drops-template#1]
Supporting Middleman v4 is WIP. See `upgrade-to-v4` branch for details.

**Comment by hovancik** [comment]
is there a TODO or something where we could see current progress?

**Comment by 5t111111** [comment]
@hovancik sorry but there is no TODO list yet. however v4 support is almost done and I just have to give it some verification. the only one big problem i have encountered so far is sometimes rendered HTML files' tags are broken, but for the moment i don't have time to investigate it. it will be very helpful for me if you want to help testing with new version of this template.

the following instruction may work for migrating middleman v3 to v4.

## Installation

After upgrading middleman gem to v4.

``` text
$ middleman init -T 5t111111/middleman-blog-drops-template#upgrade-to-v4 my-blog-v4
$ cd my-blog-v4
$ npm install
```

## Start Middleman server

``` text
$ bundle exec middleman
```

Note: You may have to shutdown and restart to correctly load assets, I have not investigate the cause of this problem though.

## Migrate site settings to the new site

Migrate your site settings from `config.rb` to `data/settings.yml`. If your current settings in `config.rb` are kind of like:

``` ruby
###
# Site Settings
###

# set site URL
set :site_url, 'http://blog.example.com'
# set site title
set :site_title, 'Drops Template'
...
```

Set these settings in `data/settings.yml`.

``` yaml
site_url: 'http://blog.example.com'
site_title: 'Drops Template'
site_description: 'Site Description'
site_author: 'Site Author'
```

## Copy your contents to the new site

Copy all contents you created in `source/posts` and `source/images` to the corresponding directory in the new site. Maybe you want to copy your stylesheets if you have changed them.

**Comment by hovancik** [comment]
I am working on one blog so I will use v4 and report if I have any issues

**Comment by 5t111111** [comment]
@hovancik thanks :smile: 

> the only one big problem i have encountered so far is sometimes rendered HTML files' tags are broken

FYI i've found the cause of this problem, it's not middleman-related issue, but the one related to redcarpet (vmg/redcarpet#538) . so this problem occurres only in case that you want to use non-ascii characters like japanese in your articles' headlines.

**Comment by hovancik** [comment]
```
Asdf.

Dsfg.
```

is producing 
```
Asdf.
Dsfg.```

I guess that's also redcarpet?

**Comment by 5t111111** [comment]
@hovancik That is general behavior of markdown, so you'll see the same even if you change markdown engine from redcarpet to kramdown.

When yoiu write

```
Asdf.

Dsfg.
```

it produces 

```html
<p>Asdf.</p>
<p>Dsfg.</p>
```

tha means if you want more line-spacing, you can simply add some vertical margin to `<p>` in `_base.scss`. Or if you want `<br>` rather than `<p>` you can write it like this (don't forget two trailing spaces at the end of line 1).

```
Asdf.  
Dsfg.
```

In fact, although i think it would better `<p>` tags have some vertical margin out of the box, I hesitate to add them as it could break the existing articles layout. Pull requests are always welcome though.

**Comment by hovancik** [comment]
you're right. I didn't notice that it's css thingy

**Comment by 5t111111** [comment]
I've decided to change the default markdown engine to kramdown instead of redcarpet because of the problem referenced the above comments.

**Comment by 5t111111** [comment]
Closing this issue as now middleman v4 support is the default.
