### ISSUE TITLE
404 page won't be displayed properly on GitHub Pages

### ISSUE THREAD

**Issue by 5t111111** [5t111111/middleman-blog-drops-template#3]
I haven't tested yet but this issue was reported in http://blog.takumi-onodera.work/2015/12/07/middleman-github-pages/

**Comment by it-praktyk** [comment]
I confirm an issue. The same is when I'm using Bitbucket.org repository and aerobatic.com hosting - e.g. https://it-praktyk.pl/nonexisting

**Comment by 5t111111** [comment]
@it-praktyk Thank you for your confirmation 😄 

I've changed `404.html.slim` not to use directory index so that it would fit GitHub Pages requirements for error pages.

ATM I'm not sure it also fixes the problems with Bitbucket.org and aerobatic.com hosting though.
