### ISSUE TITLE
The missing dependency to activesupport ?

### ISSUE THREAD

**Issue by it-praktyk** [5t111111/middleman-blog-drops-template#7]
Hi,
the blog create with the newest blog-drops template under build process warning is displayed - details below

```
[user@host]$ middleman build
WARN: Unresolved specs during Gem::Specification.reset:
      activesupport (>= 3.1, ~> 4.2)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/<user>/.gem/ruby/gems/middleman-blog-4.0.0/lib/middleman-blog/blog_data.rb:170: warning: duplicated key at line 170 ignored: :lang
== Executing: `./node_modules/webpack/bin/webpack.js -p --bail`
```

**Comment by 5t111111** [comment]
@it-praktyk 

Try `bundle exec middleman build` .

That warning is actually the one indicating missing dependencies, but it's for system wide installed middleman. Remember that you should always run `middleman` via `bundle exec` except initializing a new project.

**Comment by it-praktyk** [comment]
Thank you for explanation.
